cidr           = "10.0.0.0/16"
azs            = ["us-west-2a", "us-west-2b"]
region         = "us-west-2"
secops-profile = "default"
customer       = "f5labs"
ec2_key_name   = "mkennedy-f5labs"
ec2_key_file   = "mkennedy-f5labs.pem"
environment    = "tst"
project        = "ts"
